inc/structure/header.php
More details: https://wordpress.org/support/topic/rename-primary-menu-in-mobile-view-1
=> Fix apply_filters() for the "storefront_menu_toggle_text" filter

changelog.md, template-homepage.php
( 'storefront_homepage_content' )
=> Adds the correct page content hook in the homepage template inline docs.

inc/structure/footer.php
As per https://trello.com/c/4vjN2ld1/286-theme-footer-links
Update the footer link to include alt and title attributes.
=> Update footer link alt and title attributes

style.scss
=> www in links

inc/functions/extras.php
Borderline pedantic but I just noticed it while browsing the code and thought it was an easy fix.
=> cute type conversion removal?

sass/components/_comments.scss
I have added parent selector > .comment-body before referencing cite
=> Fixes #159

inc/structure/post.php
Added a comment in a string translation to help translators
=> Commented translation

404.php, inc/woocommerce/template-tags.php
Prevent this: http://cld.wthms.co/1aptw/1UlXRHz6
By turning it into this: http://cld.wthms.co/SIJz/1DstbzTT
Could also do a check to see if products are on sale and show that before reverting to recently added.
=> Check for featured products on 404 page

inc/woocommerce/css/woocommerce.scss
new password strength meter style added for storefront theme
=> password strength meter style added to storefront ref #245

inc/structure/hooks.php, single.php
Should these have the same priority?
https://github.com/woothemes/storefront/blob/master/inc/structure/hooks.php#L76
=> Add missing hooked function

Gruntfile.js, package.json
=> Added license in package.json

inc/admin/welcome-screen/sections/contribute.php
There's a small text typo in the welcome screen
=> Small text typo

inc/storefront-template-functions.php
=> Validation in `storefront_posted_on()`

inc/storefront-template-functions.php
https://github.com/woothemes/storefront/issues/324
Lines 753 to 781:
I Followed the same format as the other sections.
I just enabled the code for best_selling
=> 753-781 added Best Selling Products w/ identical format as other sections

inc/storefront-template-hooks.php
Add Best Selling Products for 2.0 https://github.com/woothemes/storefront/issues/324
Comment added to line 48
added_some_action_jackson to line 56
=> Add Best Selling Products for 2.0

style.scss
Changed from HTTP to HTTPS in style.css
=> Fix author and theme URL

inc/admin/welcome-screen/component-intro.php
=> Included notice for Theme Customisations

content-single.php, content.php, header.php, inc/class-storefront.php, inc/storefront-template-functions.php, inc/storefront-template-hooks.php, inc/woocommerce/storefront-woocommerce-template-functions.php, inc/woocommerce/storefront-woocommerce-template-hooks.php
Implementing dynamically generated json for categories or archives is somehow a little bit delicate...
Instead of remaking a loop to get each post data, I believe I better use an existing loop such as `storefront_loop_post`... The little problem with this approche is that I need to store the generated data from the loop outside of the loop for later use... So for this, I use a Storefront static property.
As far as my actual competences are concerned, I don't see better approche.
Let me know if you'd like me to modify anything anyway...
=> Structured data improvement

.gitignore, assets/sass/woocommerce/product-reviews-pro.scss, assets/sass/woocommerce/woocommerce.scss
other minor plugin style tweaks; see #411
=> [#411] Adds icons for Subscriptions & PRPro account tabs, + ... 

style.scss
Switch URL to https://woocommerce.com/ on style.css
=> Switch URL to https://woocommerce.com/

assets/sass/utils/_mixins.scss
I believe this is a typo.... unless I'm unaware of some strange SCSS operator. :-)
=> fixed clearfix mixin typo causing sass to fail

inc/class-storefront.php, inc/customizer/class-storefront-customizer.php
=> Fix PHP 5.2 support

assets/js/woocommerce/checkout.js
=> Checkout: Sticky Payment RTL Issue

inc/woocommerce/storefront-woocommerce-template-functions.php, inc/woocommerce/storefront-woocommerce-template-hooks.php
=> Structured Data Update Revision1

assets/js/woocommerce/header-cart.js, assets/sass/woocommerce/woocommerce.scss, inc/woocommerce/class-storefront-woocommerce.php
Related to #479.
Actually, I'm not really experimented with JS, so take a close look... :P 
My main doubts are:
1. Does Storefront support Explorer 8 ? If so, I need to make it compatible...
2. Is the frontend behaviour OK ?
3. Is there a better approach ?
=> Header Cart Dropdown Scrolling

functions.php
Updated the github theme customisation link.
=> Update the functions.php to use the correct theme customisation GitHub repo link

inc/storefront-template-functions.php
Changing footer credit from WooThemes to WooCommerce
=> Change Footer Credit from WooThemes to WooCommerce

inc/customizer/class-storefront-customizer.php, inc/storefront-template-functions.php
Required some custom code, since there's no way to make `jetpack_the_site_logo()` return values, so I had to copy and paste the code.
=> Fixed PHP 5.2 compatibility

inc/class-storefront.php
Related to #484.
To merge **after** #494 is merged (if it is in first place).
=> Fixes #484

assets/sass/base/_base.scss
=> Fix for #544

assets/sass/base/_base.scss, assets/sass/woocommerce/woocommerce.scss
Still not clear if I am doing right, but let's go.
=> Fixes for #544, #546 and enhancement of the sidebar

inc/woocommerce/class-storefront-woocommerce.php
Fixed missing/wrong arguments in inc/woocommerce/class-storefront-woocommerce.php
=> Fixed some wrongly defined arguments for wp_enqueue_style & wp_register_script

inc/storefront-template-functions.php
Improvement suggestion: remove hardcoded english texts causing unwanted result on multilingual site.
=> Translatable `aria-label`

README.md
I have fixed some minor changes in README.md file.
=> Fix minor changes in README.md file

assets/sass/woocommerce/woocommerce.scss
Fixed issue #615 "Design conflict on Checkout page with demo store notice"
=> Fixed issue #615 "Design conflict on Checkout page with demo store notice"

assets/sass/woocommerce/woocommerce.scss
=> Add padding to shopping cart drop-down

inc/woocommerce/storefront-woocommerce-template-hooks.php
remove 4th parameter being passed to remove_action, it only accepts 3
=> remove invalid parameter passed to remove_action

assets/js/navigation.js, assets/sass/base/_layout.scss
- Add access to submenus from touchscreen devices
- Add styles for keyboard navigation on focus items
=> Nav accessibility

composer.json
Copied over from WooCommerce itself and modified for Storefront.
=> Adding composer.json file

inc/class-storefront.php
=> Add child theme version to wp_enqueue_style()

CONTRIBUTING.md, package.json
Use instead the grunt version installed by this package
=> remove need to install grunt globally

assets/sass/woocommerce/woocommerce.scss
=> Price filter slider styling

inc/woocommerce/class-storefront-woocommerce.php
=> Update Bookings calendar selectors

assets/js/woocommerce/checkout.js
=> fix issue 719

assets/sass/base/icons.scss, assets/sass/woocommerce/woocommerce.scss
=> My account payment methods styling

inc/storefront-template-functions.php
Updates footer credit from "Storefront designed by WooCommerce" to "Built with Storefront by WooCommerce".
Closes #693.
=> Update footer credit

inc/storefront-template-functions.php
=> Add vcard markup to template

assets/sass/woocommerce/woocommerce.scss
=> Fix grouped products table styling

assets/sass/jetpack/jetpack.scss
=> Fix Jetpack Google Translate widget styling

inc/class-storefront.php
This allows child themes to override the args.
Closes #734.
=> Add filters to all add_theme_support declarations

assets/sass/woocommerce/woocommerce.scss
Reported here: https://github.com/woocommerce/homestore/issues/35
=> Prevent image bleed from next image in the gallery

assets/sass/base/_base.scss, inc/storefront-template-functions.php
* H1 on the front page, not posts page
* Remove margin when h1 wraps a logo image
=> Site title tweaks

assets/sass/base/_base.scss, assets/sass/base/_layout.scss
Before: https://cloudup.com/cvBVB6M4tqz
After: https://cloudup.com/cisoQag1kZW
Fixes #746.
=> 404 responsive layout

assets/sass/woocommerce/woocommerce.scss
=> Reduce padding on cart table to prevent sidebar from overflowing container

assets/js/homepage.js, assets/js/navigation.js
No warning/errors should display in the console when browsing with IE11.
Closes #795.
=> Internet Explorer 11 JS compatibility tweaks

assets/css/base/_base.scss
=> Apply styles only to author section in entry meta

README.txt
Updates and corrects readme.txt
- update links to avoid redirects
- recommend Storefront extentsions
- recommend Storefront child themes
- other minor typos
=> tweaks to readme.txt file

inc/nux/class-storefront-nux-admin.php
=> Remove nux notice if coming from WC wizard

assets/css/woocommerce/woocommerce.scss
See: https://camo.githubusercontent.com/fae284b0dd692e08234798773e87f3808a15047c/68747470733a2f2f636c6475702e636f6d2f42456779586c7a7676672e706e67
Closes #712.
=> Update My Account layout

content-single.php
Change post wrapper from **div** to **article** for single posts to improve semantic HTML.
See [_s](https://github.com/Automattic/_s/blob/master/template-parts/content.php) for comparision.
=> Improve semantic HTML for single posts

content-page.php
Change page wrapper from **div** to **article** for single pages to improve semantic HTML.
=> Improve semantic HTML for page

assets/css/base/_layout.scss, assets/css/woocommerce/woocommerce.scss, header.php, inc/storefront-template-functions.php, inc/storefront-template-hooks.php, inc/woocommerce/class-storefront-woocommerce.php, inc/woocommerce/storefront-woocommerce-template-hooks.php
* Remove breadcrumb negative margin/padding
* Remove header container and add it back as an action
* Move primary navigation outside the header container
Fixes #747.
=> Remove negative margin wrappers

header.php
=> Update reference to hooked functions in docblocks

assets/css/woocommerce/extensions/composite-products.scss
Adds some extra styles in the CP integration. Fixes some styling issues with the Summary Widget (https://cl.ly/161o2z2b1i29) when using the Fixed display mode.
=> Add missing styles to Composite Products integration

assets/css/base/_base.scss
Allow appropriate CSS to be applied to input fields with the type of `tel`.
=> Add support for `tel` type fields in forms.

assets/css/base/_layout.scss
=> Main menu alignment

assets/css/woocommerce/extensions/composite-products.scss
=> Fix composited bundles layout issues

Gruntfile.js, package-lock.json
As recommended by NPM documentation and to make sure everyone is using the same versions of all dependencies.
https://docs.npmjs.com/files/package-lock.json
cc @tiagonoronha
=> Add package-lock.json to the repository

assets/css/woocommerce/woocommerce.scss
=> Fix clearing of cart item rows on handheld screens

inc/woocommerce/class-storefront-woocommerce.php
=> Add version suffix to loaded css integration files (master)

comments.php, functions.php, inc/admin/class-storefront-admin.php, inc/admin/class-storefront-plugin-install.php, inc/class-storefront.php, inc/customizer/class-storefront-customizer-control-arbitrary.php, inc/customizer/class-storefront-customizer-control-radio-image.php, inc/customizer/class-storefront-customizer.php, inc/nux/class-storefront-nux-admin.php, inc/nux/class-storefront-nux-starter-content.php, inc/storefront-functions.php, inc/storefront-template-functions.php, inc/woocommerce/class-storefront-woocommerce-customizer.php, inc/woocommerce/class-storefront-woocommerce.php, inc/woocommerce/storefront-woocommerce-template-functions.php
This PR fixes all PHPCS errors and also most warnings. All the remaining warnings are, for the most part, related to the naming of a few class methods.
=> PHPCS errors and warnings

README.txt
=> Update changelog to reflect blog template update

README.md
correct minor typos and links in readme.md
=> typos in readme.md

assets/css/base/gutenberg-blocks.scss, assets/css/base/gutenberg-editor.scss, inc/customizer/class-storefront-customizer.php
To test:
1. Go to Customizer > Typography and change the color for the headings
2. Write a new post using the new editor, the color of the headings in the editor should be the same set in the Customizer.
Also:
1. Add a button block and change its text and background color in the side menu.
2. Button should change color in the backend and frontend.
Closes #1015.
=> Remove hardcoded color values and use values from customizer instead

assets/css/woocommerce/extensions/bundles.scss, assets/css/woocommerce/extensions/composite-products.scss
=> [Master] Hide bundle/composite child cart items below the desktop size threshold

inc/admin/class-storefront-admin.php
Updates UTM parameters as requested by the marketing team.
=> Fix UTM parameters on promotional links

assets/css/base/_base.scss, assets/js/navigation.js, inc/storefront-template-functions.php
This reverts commit bbab0ae31aeb8c6c22a62736681e7b01bea940a3.
=> Revert "Fix handheld navigation accessibility"

README.txt, languages/storefront.pot, package-lock.json, package.json, style.scss
Changes:
* Updates changelog
* Bumps version number
* Updates pot file
=> Storefront 2.4.6

inc/nux/class-storefront-nux-starter-content.php
Same as https://github.com/woocommerce/storefront/pull/1112
=> Update product categories shortcode order by in starter content

assets/css/woocommerce/extensions/composite-products.scss
=> Prevent Composite '.details' rules from affecting composited Bundles

inc/storefront-template-functions.php
=> Add filter to alter credit links

assets/css/woocommerce/woocommerce.scss
fixes #1236 by adding the button styles to storefront
=> fix password visiblity not showing #1236

assets/css/base/gutenberg-blocks.scss, assets/css/woocommerce/woocommerce.scss
fixes #1250 
it adds a well-scoped css to align the images
=> fix issue with top rated product not well aligned to the center

assets/css/base/gutenberg-blocks.scss
Fixes #1263 
<table>
<tr>
<td>Before (left aligned):
<br><br>
</td>
<td>After (left aligned):
<br><br>
</td>
</tr>
</table>
<table>
<tr>
<td>Before (right aligned):
<br><br>
</td>
<td>After (right aligned):
<br><br>
</td>
</tr>
</table>
=> Fix image alignment issue

assets/css/base/_base.scss
Fixed typo issue in css property.
1. It will fix all the veritical alignments of the button, select, input and textarea to middle.
> Fixed typo issue in css property.
=> Fixed typo in css property.

assets/css/base/_base.scss, assets/css/base/gutenberg-blocks.scss
Reverts woocommerce/storefront#1311
Woops - I accidentally merged this - hit merge button on the wrong PR. Apologies all for the confusion.
=> Revert "Do not force 0 border radius on buttons"

assets/js/homepage.js
Avoids querying for the same elements multiple times.
=> Small improvement to homepage.js

docs/releases.md, docs/testing.md
This PR adds a basic checklist of flows supported in Storefront, to aid testing. 
This is not an exhaustive list, and some of the items may need to be clarified.
Also the categories/headings are draft - keen for feedback on how to simplify this and make it useful and easy to keep up to date.
In general - keen for feedback :)
Is there anything missing - what does Storefront do/support that we should test?
Is anything not clear?
How should we organise this?
=> add basic testing flows doc (very basic)
