inc/woocommerce/template-tags.php

Let users override the function storefront_product_search.
When you use some plugins (eg. [WooCommerce Product Search](http://www.woothemes.com/products/woocommerce-product-search/)) you will probably want to use that AJAX form in the header.
Now you have to remove the action and add another one with a different function.

Override storefront_product_search

---

inc/woocommerce/template-tags.php

It should be possible to overwrite this function from a child-theme. It might be the case that someone needs more than just the link and the widget (or a different widget), or like me, need the classes to be different.

Added function check for storefront_header_cart

---

inc/functions/setup.php

@jameskoster Merge as desired.
Also, we should rename `sidebar-1` at some stage, as this is going to cause issues with many sidebars being generated, especially with a tool such as WooSidebars.

Reorders the sidebar registrations such that the primary sidebar is registered first. Fixes #126.

---

inc/woocommerce/template-tags.php

I think we should use `get_cart_subtotal` instead of `get_cart_total` for the header cart.
This is because if i have taxes enabled and prices excl. tax, but show prices incl. taxes in the cart/checkout, then the header cart shows the prices excl. taxes.
For me makes more sense to show them taxes incl. there too since it's a cart.

Uses get_cart_subtotal for header cart

---

.tx/config
Gruntfile.js
languages/storefront.pot
package.json

Hey @jameskoster 
Now you have the new Gruntasks:
- `tx_update`: Will create the .pot file and update the resourse in Transifex.
- `mo`: Will pull the .po files from Transifex and create .mo files
I also changed some tasks:
- `dev`: Runs the `default` and `tx_update` tasks.
- `deploy`: Rusn the `mo` and `copy` tasks.
For now I did not have any commits to the translations files.
However I believe that we could use the .gitignore not to push translations (.mo and .po) and this way you will have them only at WordPress.org, when running the `copy` task.
But that part is up to you, I'm just suggesting :p

Download languages files from Transifex and create .mo files

---

inc/woocommerce/css/woocommerce.scss

When there are more than one actions available on the account page for an order, the buttons are run together.
Before: http://cld.wthms.co/wwHD
After: http://cld.wthms.co/1hM9n

Provide spacing for multiple my-account buttons

---

inc/woocommerce/css/woocommerce.scss

As is, the debug logs are pretty hard to read, and require cursor highlighting. This is a simple patch to darken the text:)
Before: http://cld.wthms.co/1eXrC
After: http://cld.wthms.co/1diUi

Increase readability for debug info

---

inc/customizer/controls/layout.php

This will allow child themes to override Layout options. (we created a child theme that offers a 1 column layout, so had to override this class)

Check to see if "Layout_Picker_Storefront_Control" class exists

---

404.php

- Static strings (as in `echo 'hey';`) or numbers do not need to be
escaped, as there is no possibility to change them without changing the
code.
- When escaping numbers passed to query functions, `absint()` should be
used instead of `intval()`, to make sure to obtain positive integers.
- Strings that are output in HTML should be escaped with `esc_html()`
instead of `esc_attr()`.
- `esc_attr( __() )` can be written as `esc_attr__()`, same for
`esc_html( __() )`.
- Translations should always be escaped.

Fix escaping on 404

---

inc/woocommerce/css/woocommerce.scss

Fixes #214.
Slightly longer button titles provided by gateways can wrap in the wrong place. For example "Request Confirmation" from the WC Bookings plugin was causing the following to happen:
This tiny PR tells the button to wrap on line breaks when possible to avoid that from happening:

Wrap the place order button on line breaks so buttons don't wrap on characters.

---

sass/components/_media.scss

Fixes bug where embedded objects don't respond to screen width.
Example: http://mikey.link/1a2Du/35J1VCnD
With Fix: http://mikey.link/1b6tf/1NlDpeMB

Add responsive width for embed elements

---

inc/functions/setup.php
inc/woocommerce/functions.php
inc/woocommerce/integrations.php

Instead of toggling the stylesheet that’s enqueued, just tell Core where both of them are, and let Core handle the swapping in a ‘late-binding’ fashion.
Relevant core code:
https://github.com/WordPress/WordPress/blob/809baf442b/wp-includes/class.wp-styles.php#L88-L104
Also, if Storefront ever later migrates to shipping minified versions of these css in addition the normal css sources, you can specify a .min suffix like this:
```php
wp_style_add_data( 'example', 'suffix', $min );
```

Better enqueue RTL resources.

---

inc/woocommerce/css/woocommerce.scss

Fix for https://github.com/woothemes/storefront/issues/216
Screenshot (Chrome): 
Screenshot (Opera):

Shop sorting texts getting double lines

---

inc/admin/welcome-screen/sections/getting-started.php

@jameskoster Below are the fix and tweaks I have maintain:
1. Used `add_query_arg()` for customizer return and url args.
2. Use of `autofocus%5Bpanel%5D=nav_menus`  to configure menu panel focus.
Trailingslash was missing so only spinner was loading.
`site_url( '?storefront-customizer=true' )` instead of `site_url() . ?storefront-customizer=true`

Fix - Pass the path inside site_url for customizer args link

---

inc/woocommerce/css/bundles.scss

https://github.com/somewherewarm/woocommerce-product-bundles-tabular-layout - mimics the Grouped Products layout (table).
Current Storefront integration applies some rules that break the tabular layout, so I've retargeted those using `div` selectors (become `tr` when applying the tabular layout, no need to apply any custom styles there).

Add support for tabular bundles mini-extension

---

package.json

I believe that comma needs to come out to fix a json parse error i get when I do npm install. As soon as I removed it I could complete npm install.

removed comma to validate json and fix npm install error

---

Gruntfile.js

@jameskoster Following improvements:
* Exclude markdown files for deploy.
* Check linting errors before minification of scripts.
* No need of `rtlcss` in `grunt dev` as its included by default.
* In `grunt deploy` there exist no `mo` task so let's add `dev` tasks ;)
Simple!

Improve grunt workflow

---

inc/woocommerce/css/composite-products.scss

- Styles the 'Clear selections' button in a way similar to `a.reset_variations`:
ref: http://cl.ly/image/3D0X3L0U2l0k
- Fixes an issue with padding + div elements wrapped under `component_selections`. The existing rule does not remove the left padding from all child divs and in a couple instances incorrectly removes the bottom padding.

Composite Products integration tweaks

---

inc/functions/extras.php

When it comes to the question of sidebars and widgets in themes, there seem to be 2 general approaches:
1. Display some text in the widget area, encouraging the website administrator to add widgets (*cringe*).
2. Leave a blank space where the widgets should be (no direct education for the website administrator about what elements are missing).
This pull request introduces a third option, where by we adjust the layout to be full width if no widgets are present in the sidebar.
As widgets are added by default to the main sidebar, we can make a few assumptions:
1. If the website administrator doesn't want widgets in the sidebar, they'll remove these widgets.
2. If the widgets are removed, and the sidebar remains empty, the website administrator doesn't want a sidebar.
3. Not many website …

Adds logic to adjust to full-width layout if the main sidebar doesn't contain any widgets.

---

Gruntfile.js
assets/sass/vendors/_normalize.scss
style.scss

Fixes https://github.com/woothemes/storefront/issues/314 and preserves WP comments in `style.css`.
Also preserves the comment for normalize.scss since it's a vendor's file.

Minify style.css

---

inc/jetpack/class-storefront-jetpack.php

It looks like the path to jetpack.css file changed in Storefront 2.0.

Fix path to the jetpack.css file.

---

inc/storefront-template-functions.php

If WooCommerce is not installed the theme will throw a Fatal error because `is_woocommerce` is not declared.
Tested on my blog with success.
cc @jameskoster

Fix fatal error if WooCommerce is not installed

---

inc/woocommerce/storefront-woocommerce-template-functions.php

In the bottom bar, the My Account and Cart links show even if the pages do not exist.
This PR checks if there's an ID set in WooCommerce before to show them. It may not be used a lot, but it could. I have a use case already with a shop with a only one product and using One Page Checkout.

Remove My Account and Cart link if pages do not exist

---

inc/storefront-template-functions.php

If not using a secondary nav menu, you end up with an empty <nav> tag which
messes up the layout of the search bar which get pushed below the title/logo.
This also causes the header to be larger than desired and looks terrible.
This patch simply checks for the existence of a secondary menu before it outputs
the <nav> tags, thus not echoing an empty <nav> tag if you don't use a secondary
nav menu.

Added check for existence of secondary nav menu

---

inc/storefront-template-functions.php

Check if `storefront_primary_navigation_wrapper` or `storefront_primary_navigation_wrapper_close` exists. They might be already defined in a child theme.

Check if functions exist

---

inc/woocommerce/storefront-woocommerce-template-functions.php

I've noticed a bug on line 370 when I was preparing this [PR for woocommerce](https://github.com/woothemes/woocommerce/pull/11455).
So let's keep in mind that if they accept it, we'll have to delete the `storefront_woocommerce_init_structured_data` function when they will merge it to the stable Woocommerce.

Structured Data Fix & Tweaks

---

assets/sass/woocommerce/bundles.scss

Just noticed this in the WC Bundles integration sass - is the zero-margin rule critical? 
Can't think of any reason to eliminate the default margins there.

Remove zero margins in bundles.scss

---

assets/sass/base/_base.scss
assets/sass/components/_media.scss

I had to change this, since looks like we don't have any `%clearfix` placeholder on Storefront. And of course, or we use a mixin or a placeholder :P
```
$ grunt sass
Running "sass:dist" (sass) task
>> Error: ".clear" failed to @extend "%clearfix".
>>        The selector "%clearfix" was not found.
>>        Use "@extend %clearfix !optional" if the extend should be able to fail.
>>         on line 195 of assets/sass/base/_base.scss
>> >> 	@extend %clearfix;
>>    -^
Warning:  Use --force to continue.
```

Fixed missing %clearfix placeholder

---

content-single.php

The function name in the comment appears to be incorrect.
"storefront_single_post_after" is also referenced in single.php, but I'm not entirely sure what it's relationship to "storefront_single_post_bottom" might be.

update reference to function name in comment

---

header.php

html5bp changed doctype and here's their reasoning https://github.com/h5bp/html5-boilerplate/issues/1522
laravel also changed it few days ago https://github.com/laravel/laravel/pull/4241

doctype in lowercase

---

inc/admin/class-storefront-admin.php

Currently the "Support" link on `/wp-admin/themes.php?page=storefront-welcome` links to `https://support.woocommerce.com/` which is non-existent. Changing link to WordPress.org support forum page.

amend support link in admin header

---

inc/class-storefront.php

childtheme or plugin can hook to add extra sidebar without writing extra widget init hook and also this will work the same way other sidebar work
So, I suggest before sidebar register loop starts put a hook
$sidebar_args = apply_filters( 'storefront_sidebar_args', $sidebar_args );

Custom sidebar hook facility

---

inc/jetpack/class-storefront-jetpack.php

At the moment Jetpack infinite scroll options are not being honoured because the theme is manually set to only allow the "button" option.
Closes #689.

Remove hardcoded Jetpack infinite scroll setting.

---

inc/class-storefront.php

Removed `-moz-osx-font-smoothing: grayscale;` and `-webkit-font-smoothing: antialiased;`, as suggested in #698

Remove non-standard outdated CSS

---

Gruntfile.js
inc/class-storefront.php

Adds the icons.css file to `rtlcss` in Grunt.
* Run Grunt to generate the new file
* Use the RTL Tester plugin and the example from the issue to test
Closes #699.

Add RTL support to icons.css

---

assets/sass/base/_base.scss
assets/sass/utils/_mixins.scss
assets/sass/woocommerce/woocommerce.scss
inc/customizer/class-storefront-customizer.php

Darkened text to meet WCAG AA Passing contrast.
Addresses https://github.com/woocommerce/storefront/issues/661

Improve accessibility color contrast

---

inc/class-storefront.php
inc/woocommerce/class-storefront-woocommerce.php
inc/woocommerce/storefront-woocommerce-template-functions.php
inc/woocommerce/storefront-woocommerce-template-hooks.php

Adds support for WooCommerce 3.3 default, min, and max columns and rows and ensures backwards compatibility with older versions.
Closes #680.

WooCommerce 3.3 columns & rows

---

assets/js/homepage.js
assets/js/navigation.js
assets/js/woocommerce/checkout.js
inc/class-storefront.php
inc/woocommerce/class-storefront-woocommerce.php

Fixes #631 
Remove jquery dependency from client side code.
This PR applies 2 fixes:
- replace jQuery APIs with native DOM APIs, some examples:
- `jQuery(document).ready(...` => `document.addEventListener('DOMContentLoaded', ...`
- `jQuery(element).on('click', ...` => `element.addEventListener('click', ...`
- `jQuery(document).find(...` => `document.querySelectorAll(...`
- improve performance on `scroll/resize` events by debouncing callback to next animation frame
The admin client has been purposefully left untouched in this PR, since wordpress itself relies on jQuery.
The PR relies on `NodeList.forEach` to loop through elements, but that's not implemented in Internet Explorer, though a polyfill can be used in that case https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach#Poly …

No jquery dependency on client-side code.

---

assets/sass/base/_base.scss

This reverts commit 3b5c6da496da5a2bf3bc39a8c433362a968f8a21.
Fixes https://github.com/woocommerce/storefront/issues/738.

Revert "hotfix header overlay-x"

---

assets/sass/base/_base.scss

Before (incorrect size, 100%):
https://cloudup.com/cy_VMq8TPCJ
After:
https://cloudup.com/cF2AI24ZsHu
Closes #636.

Fix IE logo image size

---

assets/css/woocommerce/woocommerce.scss

Style other action buttons in the widget cart

---

Gruntfile.js
assets/css/woocommerce/woocommerce-legacy.scss
assets/css/woocommerce/woocommerce.scss
inc/woocommerce/class-storefront-woocommerce.php
inc/woocommerce/storefront-woocommerce-template-hooks.php

Conditionally removes columns wrapper, unnecessary as of WooCommerce 3.3, and adds a legacy CSS file that's loaded for WC version under 3.3.
Test with WooCommerce 3.2 and 3.3.
Closes #711.

Remove columns wrapper and add legacy support

---

assets/css/woocommerce/woocommerce.scss
assets/js/navigation.js

This is particularly useful for small screen android devices, where the footer bar is displayed above the keyboard, leaving less space available in the screen.
Fixes #625.

Hide handheld footer bar when an input is focused

---

inc/jetpack/class-storefront-jetpack.php

Remove Infinite scroll hacks

---

Gruntfile.js
assets/css/woocommerce/extensions/brands.scss
assets/js/woocommerce/extensions/brands.js
inc/woocommerce/class-storefront-woocommerce.php
inc/woocommerce/storefront-woocommerce-template-functions.php
inc/woocommerce/storefront-woocommerce-template-hooks.php

To test:
* Install WooCommerce Brands
* Create a few brands and assign product to them
* On the homepage, you should see a new "Brands" section
* On single product pages, you should see the brand image above the logo
* On archive pages, you should see the brand + brand description.
Designs: https://cloudup.com/c5wszle3RFk 
Closes #627.

Woocommerce Brands Integration

---

assets/css/base/_base.scss

Previously max height on sub menus was set to `1750px`. Sites with a large menus were only showing a portion of the items.
This PR increases that number to `9999px`. 
The enhancements to the menu added in #669 also make this issue unlikely to be a problem again, since sub menus are hidden by default.
Closes #798.

Increase max-height for sub menus

---

assets/css/woocommerce/woocommerce.scss

This PR reverts https://github.com/woocommerce/storefront/pull/749.
Since in the end this is an issue with Flexslider, I'll open an issue there.
Closes #810.

Remove gallery negative margin

---

assets/js/sticky-add-to-cart.js
inc/woocommerce/storefront-woocommerce-template-functions.php

Because the sticky button element is now on by default, it might make sense to ensure it works reliably with non-core product types. I did some tests and found a couple issues -- hopefully this PR addresses them well. 
1. The sticky button text is not generic enough. A more suitable method to populate it might be `add_to_cart_text`. My feeling is it works a bit better than the existing conditional logic that uses `single_add_to_cart_text`. It produces the expected result with all product types I tested.
2. Allow customizing the "trigger" element. Some product types may include options to display add-to-cart form content after the 'entry-summary' element. In such cases, the sticky-button behavior should be customizable (ideally) to work reliably.

[2.3] Improve sticky button behavior with non-core product types

---

assets/css/admin/welcome-screen/welcome.scss
inc/admin/class-storefront-admin.php

Remove free extensions column from welcome page

---

assets/css/base/_base.scss
inc/storefront-template-functions.php

Adds 'Privacy link' to footer:
Adds padding to labels after checkboxes:
This PR requires WordPress 4.9.6.
Fixes https://github.com/woocommerce/storefront/issues/835.

WordPress 4.9.6 + GDPR

---

assets/css/base/_base.scss
assets/css/base/_layout.scss

Clears floats in `.col-full` globally across all viewport widths.
Closes #854.

Apply clearfix to col-full div globally

---

assets/css/base/icons.scss

This PR changes the way the CSS is compiled for the `icons.scss` file, fixing the issues reported in #853.
Fixes #853.

Remove Sass extend from icons

---

inc/customizer/class-storefront-customizer.php
inc/woocommerce/class-storefront-woocommerce.php

There's no need for a CSS cache since `theme_mod` are options and options are autoloaded. There's no advantage to having a cache.
This PR removes the caching mechanisms and deprecates all methods that are no longer necessary.

Remove inline CSS cache

---

assets/css/woocommerce/woocommerce.scss

Move breadcrumb margin and padding to new wrapper so that when adding a background to the wrapper, there's no unwanted spacing.
Closes #871.

Move breadcrumb margin and padding to new wrapper

---

assets/css/base/_base.scss
assets/css/base/_layout.scss
assets/css/woocommerce/woocommerce.scss

To test, check if the site title and menu button show side by side on mobile devices, and that the title is clickable on mobile:
Closes #872.

Revert global col-full and remove relative positioning from header col-full

---

assets/css/base/icons.scss

Remove `font-weight` that is currently preventing the new Font Awesome icons from displaying on the handheld footer bar.
Closes #878.

Remove legacy font weight

---

assets/css/woocommerce/woocommerce.scss

The recent changes to the breadcrumb wrappers seem to have increased the size of the breadcrumbs bottom margin, this PR reduces the size of the margin.
Compare 2.2 vs 2.3 to see the difference in size.

Decrease breadcrumb bottom margin

---

inc/storefront-template-functions.php

H1 should only be applied to the Blog page to ensure that only one `H1` heading is ever present on a page.
For example, in the Homepage template, the "Welcome" section is the `H1`. In the blog page, all posts are `H2` headings, so the site title becomes the main `H1`.
Closes #874.

H1 site title only in blog page

---

assets/css/woocommerce/extensions/memberships.scss

Memberships mobile table layout

---

inc/storefront-template-functions.php

Replaces the old deprecated shortcodes with the new ones.
It also fixes an issue where top rated products were not ordered correctly.
Closes #892.

Update homepage shortcodes

---

assets/css/sass/utils/_mixins.scss

Removes sass mixins that haven't been in use for a long time. 
To test, compile Sass. If no errors, 🎉!
Closes #891.

Remove legacy Sass mixins

---

inc/woocommerce/storefront-woocommerce-template-functions.php

Replaces `wp_kses_data()` with `wp_kses_post()` in places where previously WC html was being stripped out.
Output of the mini-cart and Sticky Add-To-Cart should stay the same after this change.
Closes #886.

Use WC default HTML output for better compatibility with extensions

---

assets/css/woocommerce/extensions/brands.scss

see bug https://github.com/woocommerce/storefront/issues/907 
The brands.scss contains incorrectly scoped css in the brands integration, that applies to all h3 tags here: assets/css/woocommerce/extensions/brands.scss#153
This change was introduced in the Woocommerce Brands Integration #803 PR (#803).
The fix is easy, to move the the global h3 selector inside the div#brands_a_z selector in the brands.scss file.

Fix #907 h3 scoping issue in woocommerce brands integration

---

assets/css/woocommerce/woocommerce.scss

We use the title in the `data-title` attribute to display the title in responsive tables. This change makes sure we only add the title if the data attribute exists in the column.
Otherwise you get an empty `:` (colon) when no title exists in the column.
To test, go to My Account > Orders > View order. Resize your window. Remove the `data-title` from one of the columns. Without this PR you'll see a a colon with no title.
Closes #910.

Only add title to columns with data title attribute

---

inc/class-storefront.php

Allowing this also 'enables' the "Skip Cropping" button in the Media Library UI.

Allow for a flexible height on the site logo

---

assets/css/base/_base.scss

Removes the default from `a` links, it's by default 400 in every browser.
This change enhances compatibility with web site builder plugins. 
Closes #920.

Remove font weight from from a/link elements 

---

header.php

This PR fixes WCAG 2.0 (AA) violation by enabling zooming and scale. Being able to zoom is essential for users with low vision.
Test in before/after in Chrome mobile. With this PR you should be able to pinch to Zoom.
Closes #919.

Accessibility: Allow zooming

---

assets/css/woocommerce/woocommerce.scss

For both RTL&LTR sites, the price slider widget label should display from left to right $1 - $100.
See the following PRs or #921 for more information:
https://github.com/woocommerce/woocommerce/pull/20417
https://github.com/woocommerce/woocommerce/pull/20221
Kudos @mikeyarce. :)
Closes #921.

LTR price filter label when in RTL

---

inc/storefront-template-functions.php

Remove support for legacy Jetpack logo. 
Closes https://github.com/woocommerce/storefront/issues/916.

Remove legacy Jetpack logo

---

inc/customizer/class-storefront-customizer.php

Like all other links in the header, the color for the handheld dropdown handle should be the same as of the other header.
To test:
* Go to Customizer > Header and change the color of the links. 
* Resize the browser window
* The dropdown handle should have the color selected in the Customizer
Closes #934.

Handheld navigation dropdown toggle color

---

assets/css/woocommerce/woocommerce-legacy.scss
assets/css/woocommerce/woocommerce.scss

In https://github.com/woocommerce/storefront/pull/779 we added support for the columns wrappers in WC 2.3.
This PR remove the static CSS for the 3 columns in related products and inherits the CSS from the columns wrapper.
Also keeps backwards compatibility by adding the removed CSS to the legacy file.

Remove static related/upsells columns size

---

assets/css/base/_base.scss
assets/css/woocommerce/woocommerce.scss

Fixes overflow issue noticed in https://github.com/woocommerce/woocommerce/issues/20756#issue-340209496
* Sets global select `max-width` to `100%`
* Sets variations select `max-width` to `75%` so that the "clear" button is able to line up side by side with the dropdown.
Before:
After:

Prevent select from overflowing container

---

inc/woocommerce/class-storefront-woocommerce-customizer.php

In https://github.com/woocommerce/storefront/pull/912 we moved everything that is WooCommerce into separate contained files.
This PR changes the way the default values for settings related to WC components are set. Instead of having its own method and filter, I think it makes more sense to filter the main list in the main class.
This way we don't have to filter two times.

Filter main theme mods array

---

Gruntfile.js
assets/js/admin/customizer.js
inc/nux/class-storefront-nux-guided-tour.php

Before:
After:
To test:
1. Use a plugin like "RTL tester" to switch the site to RTL mode.
2. Run grunt to generate the new rtl file.
3. Visit the Customizer and confirm that the Guided tour "bubble" is positioned correctly.
You only get the "Guided Tour" the first time you visit the Customizer. If your test environment is a existing site, go to /wp-admin/options.php and set `storefront_nux_guided_tour` to `0` and then visit the Customizer.
Closes #964.

Add missing RTL support to customizer guided tour

---

assets/css/woocommerce/extensions/bundles.scss
assets/css/woocommerce/extensions/composite-products.scss
inc/woocommerce/class-storefront-woocommerce.php

This PR:
* Introduces new styles for Bundle /Composite-type single-product pages. Both Composite Products v3.14 and Product Bundles v5.8 include updates to the single-product page styles that need to be supported by Storefront. The change set here is backwards compatible with previous PB/CP versions.
* Adds support for some advanced theme features in CP/PB which improve the way Bundle/Composite child items are displayed on handheld screens in the cart (older PB/CP versions aren't affected):
See #969

Support CP 3.14 and PB 5.8

---

assets/css/base/_layout.scss

Sometime when we slightly refactored the header, this change was introduced, but it overrides other CSS rules that set the logo to a specific size.
This could cause some unwanted behaviour when changing  the size of the `.site-branding` container.
With this change, the logo image will inherit the size from a different selector and will always be set at `230px`.

Remove rule that sets logo image 100% width if WC active

---

assets/js/navigation.js
assets/js/vendor/pep.min.js
inc/class-storefront.php

This issues affects primarily devices that are touch enabled, but also have mouse like Windows Surface tables. 
This fix ensures that dropdowns are navigable when using a mouse and also when tapping on the screen. 
It uses the Touch Events API to distinguish between the different types of events. Since this API is not supported across all platforms and browsers, I'm including [PEP](https://github.com/jquery/PEP), a polyfill created by the jQuery foundation (does not require jQuery).
To test:
1) Create a menu with nested items (dropdowns)
2) Using a mouse, you should be able to hover the top item to reveal the menu and click on an item to navigate to a page.
3) Using a touch screen device, when tapping on the top item, the first screen should open the dropdown. Tapping again on the top …

Use Pointer Events API for consistency across touchscreen devices

---

inc/woocommerce/class-storefront-woocommerce.php

Use class already initialised in global `$storefront` object instead of creating a new instance.
Closes #996.

Stop Storefront_Customizer class from being instantiated twice

---

assets/css/woocommerce/extensions/bundles.scss
assets/css/woocommerce/extensions/composite-products.scss
inc/woocommerce/class-storefront-woocommerce.php

Port of #970 to master.
2.4.0 is now organized in a way that ensures `class-storefront-woocommerce.php` is only loaded when necessary -- so this PR includes a new `storefront_woocommerce_setup` hook to make it easier for WC integration code to be added in the future.

Add CP 3.14 and PB 5.8 integrations to master

---

Gruntfile.js
assets/css/base/_base.scss
assets/css/base/_layout.scss
assets/css/base/gutenberg-blocks.scss
assets/css/base/gutenberg-editor.scss
assets/css/base/icons.scss
inc/class-storefront.php
inc/customizer/class-storefront-customizer.php
inc/storefront-template-functions.php
inc/storefront-template-hooks.php
inc/woocommerce/class-storefront-woocommerce.php

This PR adds enhanced compatibility with the upcoming WordPress editor. Changes introduced in this PR:
* Declare support for Gutenberg features
* Styling for blocks included with the editor
* Change the single post layout from having the post meta to the left of the content to allow for blocks to go full width
* Add CSS file for future editor styles
**Post meta before:**
**Post meta after:**

Compatibility with Gutenberg editor

---

inc/storefront-template-functions.php

Fixes and issue where the text 'Posted on' is slightly bigger in size than the rest of the post meta content.
Before:
After:

Move 'posted on' inside span

---

assets/css/base/gutenberg-blocks.scss
inc/class-storefront.php

Adds a custom body if the current theme supports Gutenberg's align-wide option.
This is useful for child themes that don't support this option so that we don't have to manually reset styles on each child theme individually.
To test, see if the `storefront-align-wide` shows up in the list of `body` classes.

Add custom body class if align-wide is supported

---

inc/class-storefront.php

The trailing slash is not required in the first load_theme_textdomain() call.
It results in a search for: /wp-content/languages/themes//en_US.mo 
It's not harmful but simply inconsistent and unnecessary.

Remove unnecessary trailing slash

---

functions.php
inc/jetpack/class-storefront-jetpack.php
inc/woocommerce/storefront-woocommerce-functions.php

In Storefront 2.4 we reorganized the file structure for the theme and ended up forgetting to include one of the files - `storefront-woocommerce-functions.php`
This file contains the `storefront_is_product_archive()` function that is used in our Jetpack Infinite Scroll integration. Without this file, users using this option will get a fatal error when trying to dynamically load new products.
I've also refactored the code a little bit:
* Removed the now unnecessary `storefront_is_woocommerce_activated()` check since this file will only load when WooCommerce is active.
* In the Jetpack integration file, check if the `storefront_is_product_archive()` function exists.
To test:
* Install Jetpack. I recommend using debug mode so that you don't have to deal with authentication with WP.com and …

Add missing WC functions file include

---

Gruntfile.js

Add `composer.lock`, `phpcs.xml`, and the `vendor` folder to the list of excludes in the Copy task.
Also adds `dev` to the deploy `task` to ensure everything is built and up to date when generating a new build.

Update Grunt copy task file excludes

---

assets/css/base/gutenberg-blocks.scss
assets/css/base/gutenberg-editor.scss

Updates the order of the Sass imports. Without this PR Sass files are not compiled correctly and some of the variables do not translate into values.
For example, in `gutenberg-blocks.css`
`@media (min-width: 66.4989378333em)`
and not
`@media (min-width: ms(18)) {`
This isn't a problem in the current live version of the theme in WordPress.org since I spotted the issue before deploying it.

Update order of sass imports in Gutenberg Sass files

---

assets/css/base/gutenberg-blocks.scss

This clears floats on wide/full blocks. This is necessary for when there's a block with another one floated to the left/right such a paragraph + image.
Before:
After:

Clear floats on alignwide and alignfull blocks

---

inc/woocommerce/class-storefront-woocommerce-customizer.php

In 2.4 we moved all WooCommerce related code to separate files. In the process we incorrectly changed the name of CSS filter from `storefront_customizer_woocommerce_css` to `storefront_woocommerce_customizer_css`.
This PR reverts this change. 
Closes #1030.

Revert filter name: storefront_customizer_woocommerce_css

---

inc/customizer/class-storefront-customizer.php

In some methods of the `Storefront_Customizer` class we're calling the `get_storefront_default_setting_values()` method using the static `self`, and in others we use `$this`.
While looking into this, I noticed there's no specific reason why this method needs to be declared as static. The `Storefront_Customizer` class is initialized in `functions.php` in the global `$storefront` object, so the method is always available.
For that reason, I've switch all calls to `$this` instead of `self`.
Closes #1013.

Standardize mixing of static/non static function calls

---

inc/woocommerce/class-storefront-woocommerce.php

Since `$storefront` is a global variable, there have been instances where users have replaced or removed some of the methods assigned to this variable (see `functions.php` for the assignments).
This PR adds a series of conditional statements to try to mitigate this case where a class may not longer be being loaded.

Check if object is in the expected format and has right properties

---

inc/storefront-template-functions.php

Refactor posted meta `sprintf` output and separate the different elements for a better readability.
The output should stay the same in posts:

Refactor posted on sprintf

---

.gitignore
Gruntfile.js
assets/css/base/gutenberg-editor.scss
assets/js/src/editor.js
inc/class-storefront.php
package-lock.json
package.json

**What does it do**
There are two types of types of layout configuration in Storefront: with or without a sidebar.
Storefront is smart enough to automatically adapt its layout. If there are widgets in the main sidebar, then the content will adjust and display the sidebar. Otherwise, when there are no widgets in the sidebar, it will always display the full width layout.
On pages, it's also possible to use the full width template to allow the content to span the full width of the site.
This PR replicates this behaviour in the new blocks editor:
* When the layout is full width, the new alignment options `wide` and `full` are made available.
* If the page/post being edited has a sidebar, `wide` and `full` options are dynamically removed and any existing blocks with this alignment set will …

Dynamically update block editor layout and styling

---

assets/css/base/_base.scss
assets/css/base/icons.scss
inc/storefront-template-functions.php

Updates the post taxonomy design to be more inline with the similar design present on Product pages. Since the design on Product pages has been there for a very long time, I think it makes sense for both to be the same.
As a reminder, the icons you see in the screenshots below were introduced in 2.4.
Before:
After:

Update post taxonomy design to match design from Products

---

functions.php
inc/woocommerce/class-storefront-woocommerce-adjacent-products.php
inc/woocommerce/storefront-woocommerce-functions.php
inc/woocommerce/storefront-woocommerce-template-functions.php

Ever since we incorporated Product Pagination into Storefront, there have been a few complains about the way it works:
* Invisible products break pagination
* It doesn't circle back to the begging
We have been relying on the `get_adjacent_post()` function, but its functionality is quite limited. Although it provides a good number of filters, it depends on the current global `$post` so modifications have to be very tactical.
This PR introduces a new class that addresses the complains listed above. It uses `get_adjacent_post()` where possible and a regular WC query to get the first/last item.
First we try to get a valid product via `get_adjacent_post()` adding a filter so each iteration of the loop uses the date of the next product to test. The results of this function are cached by …

Improvements to Product Pagination

---

inc/storefront-template-functions.php

Notice the extra space on the post date link, between the date and "by admin".
Before:
After:

Remove extra space from entry date link

---

assets/css/base/_base.scss

Removes padding and hover transition from the post navigation so it sits flush at the edge of the main content area.
To test, visit a regular post and look for the post navigation links at the end of the post.
Before:
After:

Remove padding and transition styles from post navigation

---

content-single.php
content.php
inc/storefront-template-functions.php
inc/storefront-template-hooks.php

In certain situations you might want to move the post meta from one hook to another. So this PR removes the direct call to `storefront_post_meta()` and then add it back via the `storefront_post_header_before` hook.
Two new hooks introduced:
* `storefront_post_header_before `
* `storefront_post_header_after`

Add hooks to post title and move post meta to new hook

---

assets/js/footer.js
assets/js/navigation.js
inc/class-storefront.php
inc/woocommerce/class-storefront-woocommerce.php

This PR moves all the JS related to the Handheld Footer Bar out of `navigation.js`. This makes things a tad bit more modular and also fixes an issue that could happen in situations where the primary navigation is unhooked and not used in the site.
To test, resize the browser to a mobile size, and click the "Search" icon. A search form should appear.

Move handheld footer bar JS to separate file

---

assets/css/woocommerce/woocommerce.scss

Right now styling for `ul.products` is limited to the main content. The "Below Header" widget area is a full width region, so it makes sense for styling to be supported there as well. This way, product shortcodes can be used there.
To test, add a text widget to the "Bellow Header" with `[products]` in the content.
Before:
After:
Closes #1062.

Add styling for product columns on the header widget area

---

Gruntfile.js

I'm currently doing some performance optimizations on my shop and noticed the unminified icon-styles.
Is there a specific reason why the CSS in the `base` folder is not minified?

Minify base css

---

assets/css/base/_base.scss
package-lock.json
package.json

* Updates Susy to 2.2.4
* Updates deprecated Sass color operations
To test, run `npm install` and then `npm run build`, you should not see any deprecated notices such as:
```
DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("variable-exists")) instead.
```

Fix deprecated Sass notices when running a build

---

assets/css/base/_base.scss
assets/js/navigation.js
inc/storefront-template-functions.php

When using VoiceOver, the handheld menu was still being read even though it wasn't visible on the page. This was because we set the `min-height` on the menu to `0` on load.
Without this PR, VoiceOver will still read the menu because technically it is there and not hidden.
* Hides handheld menu with CSS `visibility`
* Add `area-expanded` attribute to correct sections
* Add `aria-haspopup` attribute to indicated a sub menu is present
I moved the order of some of the JS inside `navigation.js`. The diff for this PR looks bigger than the actual changes.
How to test:
* Go to WordPress > Menus and add a few items to the "Handheld" location.
* Resize your browser until the mobile nav kicks in and turn on VoiceOver (⌘ + F5)
* Tab around the site to listen to the descriptions
* After you get to the …

Fix handheld navigation accessibility

---

assets/css/base/_base.scss
assets/css/base/gutenberg-blocks.scss
assets/css/woocommerce/woocommerce.scss

This PR:
* Underlines links in post content, footer, and breadcrumbs
* Outline styles
Links:
Outlines:
Closes #918.

Accessibility: Underline links, outlines

---

assets/css/base/_layout.scss

There's a transition being inherit from the mobile styles for menus:
This happens when no menu is assigned to the "Primary" menu location, and it uses the fallback.
**To test:**
1. Run `npm run build`
2. Ensure no custom menus are assigned to the "Primary Menu" location
3. Refresh Storefront, you shouldn't see the menu transition
Closes #1084.

Remove menu transition when no menu assigned to primary location

---

assets/css/base/_base.scss

Prevents the overlap of the site title and the Menu button on small screens. 
To test, add a big title to your test store, then resize the browser and check if the site title and the button display correctly.
Before:
After:
Closes #822.

Prevent overlap of site title and handheld menu button

---

assets/css/woocommerce/woocommerce.scss

Add left margin to view cart link in the "Added to cart" notice.
To test, browse to a product page and click the add to cart button. Then, resize the window and you should see some margin to the left of the "Add to cart" link where previously the link would clash with notice text.
Closes #818.

Add left margin to view cart link

---

inc/woocommerce/storefront-woocommerce-template-functions.php

This PR ensures that the "sticky add to cart" top bar only is displayed when a product can be purchased, is in stock, or is external.
* To test, create products with no price, or no stock.
* In the single product page, scroll down and check if the top bar is displayed in the single product page
Closes #866.

Don't show sticky add to cart if product cannot be purchased

---

inc/customizer/class-storefront-customizer.php

Adds custom color set in the Customizer to missing elements.
To test:
* Go to the Customizer > Typography
* Change the "Link / accent color"
* Go back to the frontend
* Click on the Search form in the header
* Focus color should be the same as set in the Customizer
Closes #1091

Add focus color override to all input methods

---

assets/css/woocommerce/woocommerce.scss

Before:
After:
Notice the outline around the country and Terms & Conditions checkbox.
To test:
* Add a product to card and then go to the Checkout page
* Hit the "Place order" button
Closes #778 .

Add outline to T&C checkbox and country select

---

assets/css/woocommerce/woocommerce.scss
inc/storefront-template-functions.php
inc/storefront-template-hooks.php
inc/woocommerce/storefront-woocommerce-template-hooks.php

Adds an edit link to posts, pages, and products.
Posts/pages:
Products:
To test, check that the edit links shows up in all the locations listed above.
Closes #1083.

Add edit link to posts, pages, and products

---

assets/css/base/gutenberg-blocks.scss

For some reason in MS Edge the CSS calc function calculation is a bit off which causes block gallery items to not align correctly. This PR switches the calculation of the width to use Sass math instead.
To test, add a gallery block with 4 columns to a page. Then test in Edge and check that 4 images are displayed per row.
Closes #1095.

Replace CSS calc with Sass math

---

assets/css/woocommerce/extensions/composite-products.scss
assets/js/footer.js

Changes in this PR:
(1)
Composite Products 4.0 has introduced buttons in **Options Style > Thumbnail** grid elements, and dropped box shadows previously used in various places. No changes are necessary in Storefront, aside from a small visual enhancement: https://cl.ly/14dbc63ce1e6
(2)
CP 4.0 includes many accessibility improvements. One of them is to move focus when transitioning between steps, or choosing new component options, which also allows screen readers to announce the newly focused elements (in all cases non-form elements with `tabIndex=-1`).
Storefront includes some code to show/hide the mobile footer bar when _any_ page element takes focus. This is done by adding/removing an element on `body`. Long-term, it might be a good idea to limit this behavior to input/textarea elements …

Add Composite Products 4.0 support

---

assets/css/base/gutenberg-blocks.scss
assets/css/woocommerce/woocommerce.scss
inc/customizer/class-storefront-customizer.php
inc/nux/class-storefront-nux-starter-content.php
inc/storefront-template-functions.php

<p>With the new WC blocks in WooCommerce 3.6, we can now replace our old homepage page template (template-homepage.php) with a new editable block based homepage.</p>
<h3>New cover block in WordPress 5.2</h3>
<p>Starting in 5.2, the cover blocks now includes an inner container where it&#8217;s possible to add headings, paragraphs, and buttons.</p>
<p>Here&#8217;s an example:</p>
<p><strong>How to test</strong></p>
<ul>
<li>Install WP 5.2 beta or Gutenberg plugin from WordPress.org</li>
<li>Create a new post/page and add a cover block</li>
<li>Add blocks inside the cover block, check that the styling matches that of Storefront.</li>
<li>Colors can be adjusted in the sidebar.</li>
</ul>
<h3>Blocks homepage</h3>
<p><code>_homepage_blocks_content()</code> is the content to add to the page, but …

WP 5.2 cover block + Blocks Homepage

---

assets/css/base/icons.scss
assets/css/woocommerce/woocommerce.scss

To test, add product to the cart and check the color and size of the remove icon.
Before:
After:
Closes #812.

De-emphasise the "remove" icon in the cart

---

inc/woocommerce/storefront-woocommerce-template-functions.php

Since pretty much the very beginning, we had the `orderby` for the products shortcode used in the Homepage template set to `name`, but due to a bug in WooCommerce this value was never enforced. 
WC 3.6.2 fixed the issue and now several customers reached out saying that the expected behaviour is for the categories in the homepage to follow the order set in the backend, which makes sense.
This PR updates the `orderby` value from `name` to `menu_order`.
To test, create a page and assign the "Homepage" template to it. Then, reorder product categories in wp-admin and check that the order changed in the Homepage.
Closes #1111.

Change homepage template product_categories orderby

---

assets/css/woocommerce/woocommerce.scss

At the moment the Product Pagination is showing up on top of the PhotoSwipe full width image preview, this PR updates the z-index values to be lower than PhotoSwipe.
To test, check that Product Pagination is enabled in the Customizer. Then visit a product page and click on the magnifier icon to go full width on the image preview. You shouldn't see the product navigation buttons.
Before:
Closes #1113.

Change product pagination z-index for compatibility with PhotoSwipe

---

assets/css/woocommerce/woocommerce.scss

if the original length of the mini shopping cart surpasses the end of the page, we get an additional scrollbar showing up.
This only happens when the cart contents is really long and the page contents is relatively short. So it's best to reproduce with a short page, or lots of variable products in the cart which take up more horizontal space.
On initial page load the double scrollbar is shown, but as soon as we hover over the mini cart it disappears. This is because the JavaScript code is triggered which reduces the height of the cart and adds the scrollbar.
In this PR we set the height to 0 and then back to auto when the cart is revealed on hover.
To test:
* Add a lot of products to the cart
* Resize the height of your browser window
* You should see a double scrollbar without this PR …

Fix mini cart double scrollbar

---

inc/class-storefront.php
inc/customizer/class-storefront-customizer.php

There are two Gutenberg hooks to enqueue assets, `enqueue_block_assets` (frontend + backend) and  `enqueue_block_editor_assets` (backend only).
Until now we've been enqueuing the same stylesheet in two different places and that's not really necessary.
This PR adds a new method `block_assets()` that will load the common stylesheets to both the frontend and backend. There's also a change to the `block_editor_customizer_css()` which adds a `is_admin()` conditional to ensure inline styles for the editor are not present in the frontend.
To test, first run `npm run build`. Then, check that `gutenberg-blocks.css` is loaded in the frontend and also in the Gutenberg editor.
Also check if the inline styles are conditionally loaded in the Customizer. Look for `.editor-styles-wrapper table th` (or …

Move Gutenberg assets to Gutenberg hooks

---

assets/css/base/gutenberg-blocks.scss
inc/customizer/class-storefront-customizer.php

This PR:
* Updates Blocks homepage negative margin to apply only to layouts that support wide blocks.
* Updates dynamic Customizer values for Cover block headings from `hero_text_color` to `hero_heading_color`
How to test:
* Test with WordPress 5.2
* Create a new page, add a Cover block to it and a heading inside (h1, h2, ...)
Changing the color of the "Hero heading color" (Customizer > Typography) should change the color of the heading.

Blocks homepage css customizer

---

inc/jetpack/class-storefront-jetpack.php

The Query Monitor plugin is currently throwing a warning when Jetpack is enabled and the Infinite Scroll module is not active, or not in an archive.
To test:
1. Install Jetpack
2. Install Query Monitor
3. Activate Jetpack and go the frontend, you should see a warning without this PR.
4. When testing with this PR, the warning should be gone.
Also, enable Infinite Scroll in Jetpack > Settings > Writing. You shouldn't see a warning. 
Go to an archive or products archive and double check that `/assets/css/jetpack/infinite-scroll.css` is being enqueued.
Closes #1126.

Fix Query Monitor missing dependency warning

---

package-lock.json

This fixes the follow vulnerability in node-tar: https://nvd.nist.gov/vuln/detail/CVE-2018-20834

Fixed node dependencies with npm audit fix

---

assets/css/base/_base.scss

Currently, storefront doesn't have styling for number input type. This PR adds number input selector to Form styling to fix it. Close #1140.

Fixed: Missing styling for number input type #1140

---

assets/css/woocommerce/woocommerce.scss

Styles the price filter on resolutions between 768px and 1024px.
Before:
After:
To test:
* Add the Price Filter widget to the sidebar.
* Go to the "Shop" page and resize your browser
* You should see the new styles between 768px and 1024px.

Price widget styling on small screens

---

inc/nux/class-storefront-nux-starter-content.php

Adds a `is_object()` conditional check when checking if `nav_menus_created_posts` exists as Customizer setting. When the setting doesn't exist, `$setting` is `null`.
This fixes an edge case reported in a WordPress.org [thread](https://wordpress.org/support/topic/uncaught-error-call-to-a-member-function-value-on-null/).

Ensure customizer setting exists

---

assets/css/woocommerce/woocommerce.scss

On checkout page first name and last name form inputs were of
uneven widths. Fix #1144 by making them of equal width.

Fix uneven form input widths on checkout page

---

assets/css/woocommerce/woocommerce.scss

Storefront forces a 2-column cross-sells layout. The grid breaks when using the `woocommerce_cross_sells_columns` filter to customize the cross-sells column count. Here's what happens when we set the column count equal to 3:
Ths PR removes the forced cross-sells rule and lets the core product grid styles do their job:
closes #1149

Cross-sells grid issues when customizing columns count

---

assets/css/base/gutenberg-blocks.scss

When adding a block, the placeholder layout is currently broken.
Before:
After:
Closes #1155.

Fix cover block placeholder layout

---

assets/css/base/gutenberg-blocks.scss

Before:
After:
Notice how the image in the "before" screenshot is not aligned with the text.
To test:
* Create a new post/page and add a few paragraphs.
* Add an image and float it to the left/right.
* Ensure that the image aligns with the text.
Closes #1127.

Fix floated image alignment

---

inc/customizer/class-storefront-customizer.php

To test: 
* Add a table block
* In the sidebar, select a color under "Color Settings"
* The table should display the new color
Also test with the "Stripes" style:
Closes #1147.

Add support for table block color styles

---

assets/css/woocommerce/woocommerce.scss

Changes the size of the "Product Name" section in the checkout cart table to leave more for the sipping methods.
With sidebar (before/after)
Full width (before/after)
To test:
* Go to WooCommerce > Settings and add a few Shipping Zones/Methods
* Add a few products to the cart and proceed to the checkout
* Check the "Your order" table
Closes #1164.

Increase shipping methods cell size

---

assets/css/base/_base.scss

On small screens the logo extends beyond the its container causing it to go under the mobile menu toggle.
Before:
After:
How to test:
* Go to the Customizer and a custom logo
* Resize your browser and ensure the logo doesn't overlap
Closes #1135.

Fix logo image overlap on small screens

---

assets/css/base/gutenberg-blocks.scss
inc/class-storefront.php

This PR fixes two issues related to the cover block:
* Font size was fixed at `1.1em`
* Default paragraph color not matching frontend color
**Font size was fixed to `1.1em`**
* Add a cover block
* Add a paragraph inside the cover and add some text
* Default font size should be the same in the editor and frontend
* In the editor sidebar change the size of the paragraph text (Small, Medium, Large, Huge). Size should be the same in the editor and frontend.
**Default paragraph color not matching frontend color**
* Add a cover block
* Add a paragraph inside the cover and add some text
* By default the text color for paragraphs should be **white** both in the editor and then in the frontend
* In the editor sidebar change the color of the paragraph. Ensure the color changes in the editor and …

Fix cover block paragraph size and default color

---

assets/css/base/gutenberg-blocks.scss
assets/css/base/gutenberg-editor.scss

Add a "separator" block to the editor and then in the sidebar, select a different style. Currently the break line is not vertically align in the preview.
Before:
After:
Closes #1156.

Fix separator block styles preview

---

inc/storefront-template-functions.php

Right now it is not possible to remove the Storefront credits link in the footer without also removing the privacy link.
This PR separates separates both pieces so that they can be toggled on/off independently. It also adds a bit of extra logic in case there's no credit link, in that case we don't want the separator ` |  ` to show up.
To test, try to toggle the filters on/off and see if everything displays as expected:
```
add_filter( 'storefront_credit_link', '__return_false' );
```
```
add_filter( 'storefront_privacy_policy_link', '__return_false' );
```
Closes #1175.

Move privacy link outside credit link conditional

---

assets/css/admin/admin.scss
assets/css/admin/buttons.scss
assets/js/admin/plugin-install.js
inc/admin/class-storefront-plugin-install.php
inc/nux/class-storefront-nux-admin.php

This PR introduces a couple of changes:
- redesigned the Install WC notice to look ± as design from p7bje6-1pr-p2
- removed unused functions
Side by side browser rendering vs design:
'Design your store' notice updates:
1. Install Storefront on a clean WP without WC, it should show notice that allows user to install WC. Check the notice design in different widths of viewport, i.e. mobile/desktop mode.
2. Test WC installation and Activation via the notice.
3. Test that 'Design your store' notice appears after going through the WC OBW. Check the notice in mobile and desktop layout.
4. Test that `Let's go` link takes you to the customizer and tour through customizer works correctly.
6. Test dismissing of the notice.
7. Test that 'Design your store' notice is displayed when WC is installed and …

Make notices conform to new theme rules

---

assets/css/base/_base.scss
assets/css/base/gutenberg-editor.scss
assets/css/base/icons.scss
assets/css/woocommerce/woocommerce.scss
inc/customizer/class-storefront-customizer.php
inc/woocommerce/class-storefront-woocommerce-customizer.php

Adds extra style rules targeting the new markup within blocks. This also fixes https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/795.
Requires https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/796 which reduces CSS specificity to allow these rules to take precedence. 
Before:
After:
Not sure who is managing SF to review @peterfabian.

Introduce extra block styles

---

inc/nux/class-storefront-nux-admin.php

While reviewing #1190, I noticed a minor issue where `esc_attr_e()` was being used to escape and print translatable strings in the content part of a HTML element. `esc_attr_e()` should be used only for HTML attributes. `esc_html_e()` should be used for HTML content. This PR fixes this issue.
**Testing instructions:**
- Follow #1190 testing instructions and make sure that the modified strings are still displayed properly.
cc @peterfabian @vedanshujain

Use correct function to escape translatable strings

---

assets/css/woocommerce/woocommerce.scss

Fixes #1197.
**Before**
**After**
- Create a post with a product grid block (for example _Top Rated Products_).
- Preview the post with a Webkit browser (Safari, for example).
- Verify the first row doesn't overflow.
This PR should replace #1200 created by @vedanshujain.

Fix Products grid overflowing on Webkit browsers

---

.github/ISSUE_TEMPLATES/1-Bug-report.md
.github/ISSUE_TEMPLATES/2-Enhancement.md

Adds two issue templates to the repo - one for bugs and one for enhancements. 
When this is merged, the "New Issue" button should guide users to report issues using one of these templates.

add issue templates

---

assets/css/base/gutenberg-blocks.scss

Fixes #1230
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>

#1230: Image block options left aligned in Storefront

---

inc/woocommerce/class-storefront-woocommerce-customizer.php

Fixes #1224 
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After (Customizer » Root Section):
<br><br>
</td>
<td>After (Customizer » WooCommerce Section):
<br><br>
</td>
</tr>
</table>
**Note:**
Due to the priority settings in https://github.com/woocommerce/woocommerce/blob/7701d4b57cb20dc89e25bb7bf2ff872d85f4c535/includes/customizer/class-wc-shop-customizer.php#L298, https://github.com/woocommerce/woocommerce/blob/7701d4b57cb20dc89e25bb7bf2ff872d85f4c535/includes/customizer/class-wc-shop-customizer.php#L368, https://github.com/woocommerce/woocommerce/blob/7701d4b57cb20dc89e25bb7bf2ff872d85f4c535/includes/customizer/class-wc-shop-customizer.php#L543 and https://github.com/woocommerce/woocommerce/blob/7701d4b57cb20dc89e25bb7bf2ff872d85f4c535/includes/customizer/class-wc-shop-customizer.php#L6 …

#1224: Move 'Product Page' customizer menu under 'WooCommerce'

---

assets/css/base/gutenberg-editor.scss
assets/css/woocommerce/woocommerce.scss

1. Make sure you have at least one product on sale.
2. Create a post and add the _All Products_ block.
3. Observe it in the frontend and verify the `Sale` badge has white background. Before, it was transparent and it would cause accessibility issues with dark images.

All Products block: don't make sale badge transparent to avoid constrast issues

---

assets/css/base/_base.scss

This is a simple patch. Removing `clip-path` on focus fixes the issue.
We don't want ***all*** `.screen-reader-text` to be visible on focus, but we do want `.screen-reader-text.skip-link` to be visible.

Make skip-link focusable, keyboard accessibility

---

functions.php
header.php
inc/wordpress-shims.php

Fixes #1208 
Change: Adds the `wp_body_open` hook after the opening body tag and added backwards compatibility to it via a separate file. This change is the result of the introduced `wp_body_open` hook in https://make.wordpress.org/themes/2019/03/29/addition-of-new-wp_body_open-hook/.

#1208: Add support for the wp_body_open hook

---

inc/woocommerce/storefront-woocommerce-template-functions.php

Search engines are indexing the add to cart link from this tag. This doesn't occur within Woocommerce as an <a> tag isn't used for the button.

Prevent indexing of add to cart link

---

inc/admin/class-storefront-plugin-install.php

Fixes #1195 
In Storefront, there's an admin notice displayed when WooCommerce is not active. One of the strings used for this was not translatable. This PR wraps it in a translation function so that it can be translated.
The string is the `or` in this notice:
1. Clone this branch as a theme in your dev environment, and activate the theme.
2. Deactivate WooCommerce plugin.
3. View an admin page - should see notice. Confirm the notice is working correctly.
Note – if you've previously dismissed this notice you may need to re-enable it.

fix untranslatable string ("or") in admin notice when WooCommerce plugin is deactivated

---

inc/storefront-template-functions.php

Fixes #1229 
Replaces `rel=“author"` with `rel="noopener noreferrer"` in https://github.com/woocommerce/storefront/blob/5ab42c724973202ab22583e3b94ce92c6cf98da4/inc/storefront-template-functions.php#L140

#1229: Replace `rel=“author"` with `rel="noopener noreferrer"` in footer

---

assets/css/base/_base.scss

New WordPress components (in [`@wordpress/components`](https://github.com/WordPress/gutenberg/tree/0779690cf4345a2468e294cbab0c8f6b805073fb/packages/components)) have a button with CSS selector [`.components-button`](https://github.com/WordPress/gutenberg/blob/0779690cf4345a2468e294cbab0c8f6b805073fb/packages/components/src/button/style.scss#L1).
This PR adds `:not` exception for all link stylings in addition to existing `:not( .button )` selector.
I'm adding multiple `:not()` selectors because of support for multiple selectors inside `:not()` is [still lacking](https://caniuse.com/#feat=css-not-sel-list).
Insert following HTML to a post:
```html
<a href="#" class="components-button is-button is-default"><span>Test</span></a>
```
And enqueue style from Gutenberg in PHP: `wp_enqueue_style( …

Don't apply link styles to core components-button

---

inc/customizer/class-storefront-customizer.php

Fixes #1260 
**Before:**
**After:**
Note: The wired colour scheme had been selected for demonstration purposes. 😁

Customizer: Adjust footer heading and link color

---

assets/css/base/gutenberg-blocks.scss

Fixes #1271 
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>

Adjust margin of aligned embeds

---

assets/css/base/gutenberg-blocks.scss

Fixes #1273 / Related to #1271 
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>

Adjust margin of aligned images

---

inc/admin/class-storefront-plugin-install.php

Fixes usage of a string context, where a translator comment should have been used.
1. Run `npm run deploy`
2. Make sure the entry for this string looks like this:
```
#: inc/admin/class-storefront-plugin-install.php:113
#. translators: conjunction of two alternative options user can choose (in
#. missing plugin admin notice). Example: "Activate WooCommerce or learn more"
msgid "or"
msgstr ""
```
The current entry is as follows. This is an inappropriate use of `context` - [this string does not need disambiguation](https://developer.wordpress.org/apis/handbook/internationalization/internationalization-guidelines/#disambiguation-by-context).
```
#: inc/admin/class-storefront-plugin-install.php:113
msgctxt ""
"Translators: conjunction of two alternative options user can choose (in "
"missing …
```

i18n: fix wrong usage of context instead of translator comment

---

Gruntfile.js

Fixes #
Grunt takes care of replacing directional icon arrows with their RTL counterparts, but a couple of heavily used icons are missing.
Before - the arrows are pointing to the wrong direction:
After:
1. Set your site language to a RTL language (Hebrew, Arabic) or use the RTL Tester plugin
2. Add a product to the cart and check out the card popover arrows
> Fix Next/Previous and forward icons in RTL mode.

icons: convert a couple additional arrows in RTL

---

Gruntfile.js
inc/nux/class-storefront-nux-admin.php

The CSS for the admin nux notice does not have an RTL counterpart, and the layout is broken in RTL languages.
Before:
After:
1. On a new install, see the notice with and without this patch.
> Fix – Improve RTL support in onboarding (NUX) welcome admin notice.

admin: make sure the admin nux notice has RTL css support

---

inc/class-storefront.php

Hi,
Given this theme is written in HTML5, it should declare HTML5 support for styles and script to avoid using `type` attributes in styles and scripts.
Otherwise, W3C validator will throw a warning because of the `type` element.
This option was introduced in WordPress 5.3. For reference, see:
- https://make.wordpress.org/core/2019/10/15/miscellaneous-developer-focused-changes-in-5-3/
- https://core.trac.wordpress.org/ticket/42804#comment:32
1. Open the website on front-end.
2. Now there is no `type` attribute anymore on styles and script (and we don't have any HTML5 warning anymore on W3C HTML5 validator).
> Better HTML5 compliance for enqueued scripts and styles.

Declare HTML5 scripts and styles support for better HTML5 compliance

---

inc/woocommerce/storefront-woocommerce-template-functions.php

From https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1999, when the actions are fired from the cart block or checkout block, disable the Storefront footer bar.
1. Use with cart/checkout blocks from the product blocks plugin
2. View cart and checkout pages on mobile, or in mobile view,
3. Confirm no footer bar is shown.
> Disable the footer bar when used in conjunction with Checkout or Cart Gutenberg blocks.

Disable footer bar when using cart or checkout block

---

assets/css/woocommerce/woocommerce.scss

Fixes #1296 #1298 #1283 (images not centering)
Fixes #1288 (no margin under product images on shop/homepage)
This PR reinstates display and margin css properties for `img` elements in product lists. Specifically:
```css
ul.products, .wc-block-grid__products {
li.products, .wc-block-grid__product {
img { 
/* affects these elements */
}
}
}
```
This is essentially a revert of [this commit](https://github.com/woocommerce/storefront/commit/b4d01df9163cc2c463a348f225ea93fa3706e3ce) from [this PR](https://github.com/woocommerce/storefront/pull/1267). Based on the discussion on that PR, I think this is safe to reinstate as it was assumed redundant. 
Before (2.5.5 no bottom margin, no centering):
After (fixed) 🎉:
1. Set some small images on products - e.g. crop the existing images so they are …

Reinstate `display: block` (centering) and margins for product-related images

---

assets/css/base/gutenberg-blocks.scss

Fixes #1276 
Fixes #1280
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>
I also checked this PR against https://github.com/woocommerce/storefront/pull/1265 to ensure that it does not break that change.

Fix margin issue of non-aligned image blocks

---

assets/css/base/_base.scss

Spun off from  #1287 - https://make.wordpress.org/core/2020/02/12/changes-related-to-calendar-widget-markup-in-wordpress-5-4/
Make the styles for the _Calendar_ widget shared with the _Calendar_ block. The only visual change is that the letter & numbers of the _Calendar_ block will now be centered.
These screenshots show the _Calendar_ block on the left and the _Calendar_ widget on the right.
_Before:_
_After:_
1. Add a _Calendar_ widget in a sidebar and a _Calendar_ block in a post.
2. View them in the frontend and notice text is centered in the block.
> Text inside the Calendar block is now centered, in line with the Calendar widget.

Wordpress 5.4 compatibility - Make calendar styles shared between the widget and the block

---

inc/customizer/class-storefront-customizer.php

Fixes #1181.
_Before:_
_After:_
You will need the changes from `fix/block-editor-classnames`, so after checking out this branch, run `git merge fix/block-editor-classnames`.
1. In the customizer set your background color to `#000000` and the typography color to `#ffffff`.
2. Open the editor and type something.
3. Verify colors are honored and text is visible.
> Site's background color is now honored in the editor.

Honor background and font color in the editor

---

assets/css/base/_base.scss
assets/css/base/gutenberg-blocks.scss

Fixes #1285 
The _Buttons_ block allows specifying the border-radius, so we shouldn't force all buttons to have 0.
_Before:_
_After:_
1. Add a _Buttons_ block and add three buttons: one without changing any attribute, one setting the border radius to 50, and the other one setting the border radius to 0.
2. Verify the border radius is honored in all of them.
> Buttons blocks now respect the border radius set by the user.

Do not force 0 border radius on buttons

---

inc/customizer/class-storefront-customizer.php

Fixes #1302 
See also related issues #1260 and #1227 
This PR patches a regression introduced recently which caused the mobile footer bar icons to use the footer link color.
The mobile footer bar previously used the header colours, as it is part of the primary navigation. In certain combinations of header/footer colors the previous issue made the footer icons invisible (#1302). This PR is focused on fixing that regression, and restoring the use of header color scheme for the footer bar (as in previous versions).
These two images show a store set up with a dark theme header and body, and a light theme footer. Note the consistency of the main nav color scheme in the first screenshot. (Screenshots show new behaviour.)
Compare with the buggy previous behaviour - the footer icons are hard to …

ensure footer bar icon links use header link color, to match header bg

---

assets/css/base/_base.scss
assets/css/base/icons.scss
assets/css/woocommerce/woocommerce.scss
inc/woocommerce/class-storefront-woocommerce-customizer.php

Fixes #1221. This PR fixes several issues with `:focus` rings.
1. In Firefox, try focusing the _Remove_ button from Cart elements (try in the _Cart_ page and the _Cart_ header dropdown).
2. In Firefox, try focusing the stars from the Product page when adding a review.
3. In Firefox, try focusing the _next_/_previous_ buttons in the pagination of the _Shop_ page.
5. In any browser, with a narrow viewport, try focusing the search button in the lower bar:
4. In all cases verify the focus ring wraps only that item, without encompassing anything else neither reaching the end of the screen.
> Fixes several :focus rings mispositioned.

Fix several :focus rings

---

assets/css/base/_base.scss
assets/css/sass/utils/_mixins.scss

See related issue #1285
The underline was intended to be added to links that look like links.
_Before:_
_After:_
1. Add a _Buttons_ block.
2. In the frontend, verify they don't have an underline.
> Buttons blocks no longer show an underline.

Remove underline from button blocks

---

assets/css/woocommerce/woocommerce.scss

Fixes #1289
The recent changes to support the show password icon button (#1236 #1238) had a layout problem when the password strength indicator is visible. This PR tweaks css to prevent the strength indicator from breaking the position of the eye icon.
The fix is to force the wrapper element `span.password-input` to use display block. As this is a span, it defaults to inline. The strength indicator `div.woocommerce-password-strength` is contained within the wrapper element but is display block. As the wrapper element is intended to display on it's own line it's more consistent to make it block. This ensures that the eye icon is always positioned relative to the container span.
As part of this fix I've tweaked the size/positioning of the eye icon to use line-height and margin to match the …

fix bug with absolute positioned show password icon when password strength indicator is visible

---

assets/css/sass/utils/_mixins.scss
assets/css/woocommerce/woocommerce.scss

Fixes #1259
This PR fixes layout issues with lengthy product names on grouped product page, cart, and checkout.
`overflow-wrap: anywhere` is used to instruct the browser to wrap preserving word boundaries and if necessary, break words. (Previously the checkout used `word-wrap: break-word` which is a [deprecated alias](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap).)
I've added this as a mixin, including `word-break: break-word;` which is needed for current Safari.
1. Add/edit some products and give them names with long words - e.g. long part number `PPXJOF123456789234-5678 Semi-circular O-ring, polycarbonate, perforated`.
2. Add these products to a grouped product.
3. Test product page - confirm layout works well on all screen sizes and browsers.
2. Add to cart.
1. Test …

Wrap long product names in grouped product, cart and checkout

---

assets/css/base/_base.scss
assets/css/sass/utils/_mixins.scss
assets/css/woocommerce/woocommerce.scss

In https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2405 we renamed the `wrap-break-word` mixin in WC Blocks, it makes sense keeping it consistent in Storefront.
I also took the change to update some other mixins to use hyphens instead of camelCase.

Rename camelCase mixins to use hyphens

---

assets/css/woocommerce/woocommerce.scss

There was a CSS selector targeting product grid blocks that was not having an effect in the _All Products_ block. That's because that block has an anchor element inside `.wc-block-grid__product-title`, but SF has a `h2 a` selector that changes the `font-weight`. So the `font-weight` inherited from the parent was ignored. (Probably that's better explained by the screenshots below :point_down: :sweat_smile: )
_Before:_
_After:_
_(notice the product name font-weight is slightly thicker)_
1. Create a page with the _Handpicked products_ block and the _All Products_ block.
2. View them in the frontend.
3. Verify they have the same font-weight.
> Updated font-weight of the All Products block so it matches the other product grid blocks.

Fix product grids selector not targeting All Products block

---

assets/css/base/icons.scss

Fixes #1347
Note: Removed an obsolete CSS statement which served no purpose for the previous three years.
> Dev - Removed unused broken CSS for main navigation icons. #1347

#1347: Remove obsolete CSS statement

---

assets/css/base/icons.scss

Fixes #1345 
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>

Add brands section to Font Awesome Library

---

.github/pull_request_template.md

Fleshed out the PR template a bit more. The goal is to capture the PR submitter's understanding of the issue/problem and explain the fix.
Also includes:
- A prompt to consider and list affected [flows](https://github.com/woocommerce/storefront/wiki/Testing-Storefront:-flows-and-features).
- Clearer guidance for release notes / changelog entries.

add hints to explain the issue and fix in PR template

---

assets/css/base/icons.scss

Fixes #1319
Storefront has css to show icons in the comment area under posts:
- Document icon for comments by the post author.
- Pencil icon for edit comment button (if available).
- Reply arrow for reply button.
These icons stopped working at some point because the css class changed - presumably from `commentlist` to `comment-list`. 
This PR fixes the css selector so the icons work correctly again 🎉 
1. Clone this branch, ensure site has a blog post.
2. Comment on a post as post author - confirm comment avatar has document icon.
3. Confirm reply and edit icons are displayed when appropriate.
4. Test with different browsers, screen sizes and user roles and confirm no regressions.
> Fix – Edit, reply and author icons are now displayed in comment list form. #1319

reinstate icons in comment list forms - edit, reply, post author

---

docs/releases.md

Storefront now has a wiki with testing instructions for each release (starting with 2.5.7) and broader flows docs. 
This PR updates the release process doc to link to the wiki and encourage updating wiki testing instructions each release.
The goal here is that we consistently communicate how to test any new enhancements or improvements with each release, so that it's easier for more people/teams to assist with testing and QA. 👫👯‍♂️
Read through the [release process doc](https://github.com/woocommerce/storefront/blob/fix/release-process-testing-instructions/docs/releases.md) and confirm it's helpful and makes sense.

update release process doc to include testing instructions & wiki

---

inc/woocommerce/class-storefront-woocommerce.php

Fixes #1299.
_Before:_
_(notice the breadcrumbs are broken)_
_After:_
In order to test this PR, you will need to create a dummy Storefront child theme as follows:
`functions.php`:
```PHP
<?php
add_action( 'wp_enqueue_scripts', 'enqueue_styles' );
function enqueue_styles() {
wp_enqueue_style( 'storefront-child-style-2', get_stylesheet_directory_uri() . '/style-2.css', ['storefront-child-style', 'storefront-woocommerce-style'] );
}
?>
```
`style.css`:
```CSS
/*
Theme Name:   Storefront Child
Template:     storefront
*/
body {
border: 5px solid pink;
}
```
`style-2.css`:
```CSS
body {
border-top-color: blue;
}
```
1. Select that theme in WP-Admin.
2. Verify styles are correctly loaded and breadcrumbs don't break.
Notice, before this PR, there was a work-around to achieve the same result as …

Set storefront-style and storefront-icons as dependencies of storefront-woocommerce-style

---

docs/releases.md

Fixes #1370
This PR adds a sentence to the release process/doc about how we choose version numbers. We have been using semver since v2.3.0; this is useful info for anyone using the theme on a site, and for anyone preparing or planning a release.
Semver is designed primarily for services with APIs. We're using it in a looser way; any change that could "break" a site - e.g. a surprising change in layout or removal of behaviour could trigger a major version bump. I'm interested in feedback or examples to flesh out what major/minor/patch mean in a Storefront context.
Since 2.3.0 there have not been any major version bumps - so the next time we make a breaking change (if that happens) we'll be trying this for the first time. 
Note - in general we aim to follow the WooCommerce policy/scheme for …

document Storefront's version numbering scheme/policy (semver) in releases doc

---

.wp-env.json
e2e/specs/browser.test.js
package-lock.json
package.json

Related #1330 - this is the first step, a few follow up tasks mentioned here.
The goal here is to get a basic e2e setup so that we can incrementally add tests for front-end & admin dashboard flows. This will provide an early warning when PRs impact existing flows (catch regressions) and another automated way to test releases. Also as we build more tests this will provide a good reference for what flows are supported in Storefront.
This PR adds basic config for the following:
- A [wp-env](https://developer.wordpress.org/block-editor/packages/packages-env/) test container (server) environment, for running tests against. Could be used as a standard/default dev setup for the repo too potentially.
- Jest & Puppeteer and related dependencies. This is the combination used by other projects, …

Basic e2e test setup using wp-env, jest and puppeteer [in progress]

---

.travis.yml
package-lock.json
package.json

Part of #1330
This adds a basic travis config and necessary package.json dependencies and scripts for running e2e tests.
Test the scripts locally:
- `npm run e2e:start` should bring up a wp-env environment, on http://localhost:8801 (dev) and http://localhost:8802 (tests).
- `npm run e2e:stop` should take that environment down.
- `npm run e2e:destroy` should take the environment down and destroy container & database state.
- `npm run e2e` should run the e2e tests; requires that the test environment is running.
- `npm run e2e:ci` should bring up the test environment and run end-to-end tests against it.
Review the Travis config. The goal of this config is to run e2e tests against open PRs as a blocking check.
As far as I can tell, Travis will only start building once the config is merged to …

Add basic Travis CI config for running e2e tests on PRs

---

inc/nux/class-storefront-nux-starter-content.php

Fixes #1423
In testing, some folks surfaced a problem where the created Homepage via the starting notice for Storefront included invalid blocks. This surfaces when trying to edit the homepage. The blocks themselves render on the frontend, but the block structure invalidates when run through the block editor validation.
The blocks are recoverable, but this is a poor experience for users wanting to edit their homepage.
It looks like the starter content originally included shortcodes as a fallback when blocks were not present in the environment the theme is installed in. However it's been a while since that was the case and we can remove that extraneous fallback.
While on master:
Create a home page using this wizard:
(You can trigger this via a fresh install of Storefront, or by manipulating …

Fix incorrect starter content for HomePage.

---

assets/css/base/_base.scss

The `_base.scss` file contains some duplicated selectors with the same properties in one case, and different ones for the others. This PR seeks to simplify the concerned selectors by merging them.
> Fix - Merge duplicate CSS selectors.

Merge duplicate CSS selectors

---

assets/css/woocommerce/woocommerce.scss

Fixes #1364.
_Before:_
_After:_
1. Using Firefox, go to Wocommerce's "My Account" page
2. Click on "Addresses"
3. Click on "Billing Address" or "Shipping Address" (alternatively in web inspector add the "focus" pseudoclass
4. Verify the outline is only around the icon and doesn't overflow the screen.
> Fix – The focus outline of the My Account address icon no longer overflows the viewport in Firefox.

Fix focus outline in My Account page with Firefox

---

assets/css/base/_base.scss
inc/customizer/class-storefront-customizer.php
inc/storefront-functions.php

1. Go to the Customizer and change the background color and the button `alt` colors.
2. Go to the Cart block with a narrow viewport (simulating mobile) and verify colors are applied to the buttons and the `Proceed to Checkout` container:
| Before | After |
| --- | --- |
| ![imatge](https://user-images.githubusercontent.com/3616980/86456301-26759800-bd22-11ea-9dbc-3f7eb3023910.png) | ![imatge](https://user-images.githubusercontent.com/3616980/86456238-0fcf4100-bd22-11ea-9e2c-99bfbb912ad8.png) |
3. Now test with a Storefront child theme. Bistro is a good example because its colors are quite different:
| Before | After |
| --- | --- |
| ![imatge](https://user-images.githubusercontent.com/3616980/86457422-ef07eb00-bd23-11ea-9754-bc8372ffaaef.png) | …

Add Cart and Checkout block styles

---

inc/woocommerce/storefront-woocommerce-template-functions.php

Fixes #1188 
See #1188 for details. 
This fixes the potential for Fatal errors to occur on various non-shopper facing requests that might get triggered against a site with Storefront active.
This impacts the display of the Cart Links in the header (desktop/ large viewport width) and the footer (mobile/ small viewport). 
Follow the testing steps in [this comment](https://github.com/woocommerce/storefront/issues/1188#issuecomment-665928301):
Likely reproduce steps:
* Set up a new site with Storefront (from this branch) and WooCommerce.
* Browse to {domain}/new//wp-json/wp/v2/users/ .
* Should see fatal error in logs.
**Note:** I was unable to reproduce this fatal on a site with WooCommerce Beta 1 and WordPress 5.5 RC1 without this branch. It's possible there was something changed in …

Add defensive checks for WC Cart instance

---

inc/woocommerce/class-storefront-woocommerce-adjacent-products.php

Fixes #1411
Fixes an issue in which draft products would show up in product pagination, this is because we use `WC_Product_Query` which defaults to all core statuses like `draft` `pending` `private` and `publish`.
I could have changed this to accept `private` and `pending` as well, but I went with `publish` for now.
This change might break some stores that relies on private or pending product showing up.
This code path is only executed if we can't find adjasant products.
1. Create a new draft product (copy a product). 
2. in master, you can see the the draft visible.
3. in this branch, you will see another product.
> Fix issue with draft products showing up in pagination.

Fix Product Pagination including draft product

---

assets/css/woocommerce/woocommerce.scss

In the newest version of  WooCommerce Blocks, users can customize All Product's Product Title block, this customization is via color or font size, but those changes can contradict with any style provided by a theme, such as Storefront.
This PR skips styling for that block if a user has already selected some styling, this is done via `has-text-color` and `has-font-size` classname.
See https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2860 for more details about this behavior.
In order to test this, you will need to have WooCommerce Blocks 3.0.0 enabled in your website.
- Create a page.
- Insert `All Products` Block in it.
- Click the "Edit" button of that block.
- Now select the Product Title block.
- In the sidebar, you can change the font size for that block, …

Skip styling All Products Product Title if we have a font size or a color from the editor

---

assets/css/woocommerce/woocommerce.scss

Fixes #1444 
This PR adds icons to storefront notices while trying to maintain the same styles.
1. Go to a product page and add a product to your cart, this should trigger a success message.
2. Change a product to be sold individuality sold
3. Add more than one, you should see the error.
4. Visit cart or checkout to see a normal notice.
-
-
> Add icons to notices.

Add icons to notices and messages
